replace_list = {
    "ain't": "am not",
    "aren't": "are not",
    "can't": "cannot",
    "can't've": "cannot have",
    "'cause": "because",
    "could've": "could have",
    "couldn't": "could not",
    "couldn't've": "could not have",
    "didn't": "did not",
    "doesn't": "does not",
    "don't": "do not",
    'dont': "do not",
    "hadn't": "had not",
    "hadn't've": "had not have",
    "hasn't": "has not",
    "havent": "have not",
    "haven't": "have not",
    "he'd": "he would",
    "he'd've": "he would have",
    "he'll": "he will",
    "he'll've": "he will have",
    "he's": "he is",
     "how'd": "how did",
     "how'd'y": "how do you",
     "how'll": "how will",
     "how's": "how is",
     "I'd": "I would",
     "I'd've": "I would have",
     "I'll": "I will",
     "I'll've": "I will have",
     "I'm": "I am",
     "I've": "I have",
     "i'd": "i would",
     "i'd've": "i would have",
     "i'll": "i will",
     "i'll've": "i will have",
     "i'm": "i am",
     "i've": "i have",
     "isn't": "is not",
     "it'd": "it would",
     "it'd've": "it would have",
     "it'll": "it will",
     "it'll've": "it will have",
     "it's": "it is",
     "let's": "let us",
     "ma'am": "madam",
     "mayn't": "may not",
     "might've": "might have",
     "mightn't": "might not",
     "mightn't've": "might not have",
     "must've": "must have",
     "mustn't": "must not",
}